- id: 0
  type: waiting
  name: 未処理
- id: 1
  type: in_progress
  name: 収集中
- id: 2
  type: done
  name: 収集済
- id: 3
  type: analyze_done
  name: 解析済み
- id: 9
  type: error
  name: エラー
- id: 10
  type: analyze_error
  name: 解析失敗
